server:
  port: 9411

spring:
  application:
     name: zipkin
     instance_id: zipkin_id
  rabbitmq:
    port: 5672
    host: rabbitmq
 
  sleuth:
    enabled: false

zipkin:
  storage:
    type: mem

logging:
  level:
    ROOT: INFO

eureka:
  instance:
    hostname: zipkin  
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
    leaseExpirationDurationInSeconds: 3
  client:
    hostname: zipkin   
    enabled: true
    registryFetchIntervalSeconds: 5   
    healthcheck:
      enabled: true
    serviceUrl:
      #defaultZone: http://mpOwner:mp19181975Secret@eureka:8761/eureka, http://mpOwner:mp19181975Secret@eureka:8762/eureka
      defaultZone: http://eureka:8761/eureka


#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka:8761/eureka, http://eureka1:8762/eureka
#  instance:
#    statusPageUrlPath: /info
#    healthCheckUrlPath: /health
#    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
