version: "3.3"

services:
    
  rabbitmq:    
    image: rabbitmq    
    container_name: rabbitmq
    links:
     - zipkin
    volumes:
     - /opt/rabbitmq/logs/:/opt/rabbitmq/logs
    ports:
     - '15672:15672'
     - '5672:5672'
    networks:
     - socnet
    
  mongonode:  
    image: mongonode    
    build: ./mongonode   
    container_name: mongonode    
    volumes:
      - /opt/mongobingo/data:/data/db
      - /opt/mongobingo/logs:/data/logs
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=Abcdf
      - MONGO_INITDB_ROOT_USERNAME=BingoBongo
    command: mongod
    networks:
      socnet:
        aliases:
          - mongonode
    

     
       


  eureka:
    image: eureka   
    build: ./eureka
    container_name: eureka   
    ports:
      - '8761:8761'
    volumes:
      - /opt/eureka/logs/:/opt/eureka/logs
    networks:
      - socnet

      
  zipkin:
    image: zipkin   
    build: ./zipkin
    container_name: zipkin
    links:
      - eureka
      - mysqlnode    
    depends_on:     
      - eureka
      - mysqlnode          
    volumes:
      - /opt/zipkin/logs/:/opt/zipkin/logs     
    ports:
      - '9411:9411'
    networks:
      - socnet
  

  server1:
    image: server1  
    build: ./server1
    container_name: server1
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    links:      
      - mongonode 
      - eureka
    depends_on:     
      - mongonode
      - eureka     
    ports:
      - '2020:2020'
    volumes:
      - /opt/server1/logs/:/opt/server1/logs
    networks:
      - socnet
      
  

networks:
  socnet:
    driver: bridge
